# Based on: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

on:
  schedule:
    - cron:  "0 3 * * 2"  # at 03:00 on Tuesday
  push:
    branches: ['master']
    tags: ['v*']
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'
      version:
        description: 'Semver'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish-debian:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        python-version: ["3.11"]
        node-version: ["22"]
        os-version: ["trixie"]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2  # v4.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf  # v6.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/invenio-python-${{ matrix.python-version }}-node-${{ matrix.node-version }}-debian-${{ matrix.os-version }}
          tags: |
            type=schedule,pattern={{date 'YYYY.MM.DD'}}
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294  # v7.0.0
        with:
          context: ./debian/
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            NODE_VERSION=${{ matrix.node-version }}
            OS_VERSION=${{ matrix.os-version }}
